[versions]
kotlin = "2.3.0"
ktor = "3.4.0"
logback = "1.4.14"
kotlin-mongodb-version = "5.6.1"
koin-version = "4.1.0"
mock-version = "1.13.10"
junit-jupiter = "5.10.0"

[libraries]
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-client-content-negotiation = {module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-status-pages = {module = "io.ktor:ktor-server-status-pages", version.ref = "ktor"}
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-cors = {module = "io.ktor:ktor-server-cors", version.ref = "ktor"}
mongodb = {module = "org.mongodb:mongodb-driver-kotlin-sync", version.ref = "kotlin-mongodb-version"}
mongodb-bson-kotlinx = { module = "org.mongodb:bson-kotlinx", version.ref = "kotlin-mongodb-version"}
koin-ktor = {module = "io.insert-koin:koin-ktor", version.ref = "koin-version"}
koin-sl4j = {module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin-version"}
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
junit-jupiter = {module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter"}
mock-test = {module = "io.mockk:mockk", version.ref = "mock-version"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
